add faq question is_it_possible_to_tag_a_service_without_value
opentelekomcloud-docs/tag-management-service pull request #32
Opened 2023-08-24 08:32 UTC by robinacar

2023-10-16 08:31 UTC, tischrei commented
recheck

2023-10-16 08:51 UTC, tischrei commented on umn/source/faqs/is_it_possible_to_tag_a_service_without_value
> +============
Not enough "=" characters.

2023-10-16 08:51 UTC, tischrei commented on umn/source/faqs/is_it_possible_to_tag_a_service_without_value
> +:original_name: tms_faq_0009.html
The file misses the .rst postfix. Otherwise it will not be found.

2023-10-16 08:52 UTC, tischrei requested changes
Rename the file and add enough "=" character to the mentioned headline.

2023-10-17 07:39 UTC, vladimirhasko commented
the problem is here:

2023-10-16 08:35:02.631285 | ubuntu-jammy | /home/zuul/src/github.com/opentelekomcloud-docs/tag-management-service/umn/source/faqs/index.rst:14: WARNING: undefined label: 'tms_faq_0009'
2023-10-16 08:35:01.736087 | ubuntu-jammy | /home/zuul/src/github.com/opentelekomcloud-docs/tag-management-service/umn/source/faqs/index.rst:16: WARNING: toctree contains reference to nonexisting document 'faqs/is_it_possible_to_tag_a_service_without_value'

2023-10-26 07:58 UTC, robinacar commented
Hi Tino, I just updated the pull request. Please review as soon as possible.

2023-10-26 10:07 UTC, tischrei approved these changes

2023-11-17 08:21 UTC, tischrei commented
@robinacar you can merge it

2023-12-15 10:56 UTC, mrumpler3 commented
Hi @robinacar ,

we will add the following FAQ to the documentation:

![image](https://github.com/opentelekomcloud-docs/tag-management-service/assets/152423682/e55134e0-a222-4b8f-8ed9-c5a7822bcaf3)

This FAQ is different than you suggested.

**The reason is:**
The behavior that you described is a bug, which should not be documented rather fix it. If you use the 'N/A' tag value by purpose and you also use empty tag value for the same tag key, then you will not be able to distinguish your resources in the Financial Dashboard based on tags. Empty tag values should not be converted to anything else, these should be kept as empty Strings.

Please open an incident for this issue, because we cannot add this faulty behavior to our service documentation. The issue is at the billing chain side where this conversion happens, TMS service cannot do anything to resolve this.

Therefore I close this proposed pull request.

2023-12-15 10:56 UTC, closed without merging